image: docker/compose:1.29.2

services:
  - docker:dind

stages:
  - test

variables:
  DB_CONNECTION: mysql
  DB_HOST: database
  DB_PORT: 3306
  DB_DATABASE: laravel
  DB_USERNAME: matt
  DB_PASSWORD: password

before_script:
  - docker-compose down -v
  - cp .env.example .env
  - docker-compose build 
  - apk add mysql-client
  - docker-compose up -d
  - sleep 60s
  - docker-compose logs database
  - docker-compose exec database mysql -h database -u matt -ppassword -e "SHOW DATABASES;"

test:
  stage: test
  script:
    - docker-compose run --rm composer install
    # - docker-compose run --rm artisan key:generate
    # - docker-compose run --rm artisan cache:clear
    # - docker-compose run --rm artisan config:clear
    # - docker-compose ps
    # - docker-compose run --rm artisan test
    # - docker-compose down
