image: docker:latest

services:
  - docker:dind
  - mysql:8

stages:
  - test

variables:
  DOCKER_DRIVER: overlay2
  DB_CONNECTION: "mysql"
  DB_HOST: "database"
  DB_PORT: "3306"
  DB_DATABASE: "laravel"
  DB_USERNAME: "matt"
  DB_PASSWORD: "password"

before_script:
  - apk add --no-cache docker-compose

test:
  stage: test
  script:
    - docker-compose up -d
    - docker-compose exec -T app composer install --ignore-platform-reqs
    - docker-compose exec -T app php artisan migrate --seed
    - docker-compose exec -T app php artisan test
  after_script:
    - docker-compose down
