image: registry.gitlab.com/mattrobinson31/laravel-docker:latest
services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: laravel
  MYSQL_ROOT_PASSWORD: secret
  DB_HOST: mysql
  DB_USERNAME: root

stages:
  - test

unit_test:
  stage: test
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - php artisan test
