image: docker/compose:1.29.2

services:
  - docker:dind

stages:
  - test

variables:
  MYSQL_DATABASE: testing
  MYSQL_USER: matt
  MYSQL_PASSWORD: password
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: 3306
  DB_DATABASE: testing
  DB_USERNAME: matt
  DB_PASSWORD: password

before_script:
  - apk add --no-cache curl
  - apk add --no-cache mysql-client
  - docker-compose down -v
  - cp .env.example .env
  - docker-compose build --no-cache
  - docker-compose up -d
  - sleep 60s

test:
  stage: test
  script:
    - docker-compose run --rm composer install
    - docker-compose run --rm artisan key:generate
    - docker-compose run --rm artisan cache:clear
    - docker-compose run --rm artisan config:clear
    - docker-compose ps
    - docker-compose run --rm artisan test
    - docker-compose down
