image: docker/compose

services:
  - docker:dind

stages:
  - test

variables:
  DB_CONNECTION: mysql
  DB_HOST: database
  DB_PORT: 3306
  DB_DATABASE: laravel
  DB_USERNAME: matt
  DB_PASSWORD: password

before_script:
  - cp .env.example .env
  - docker-compose build
  - apk add mysql-client

test:
  stage: test
  script:
    - docker-compose up -d database
    #- docker-compose run --rm composer install
    - docker-compose exec -T app npm install
    - docker-compose exec -T app npm run build
    - docker-compose run --rm artisan key:generate
    - docker-compose run --rm artisan cache:clear
    - docker-compose run --rm artisan config:clear
    - docker-compose run --rm artisan test
    - docker-compose exec -T app ./vendor/bin/pint --preset=psr12 --test

