image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2
  DB_CONNECTION: "mysql"
  DB_HOST: "database"
  DB_PORT: "3306"
  DB_DATABASE: "laravel"
  DB_USERNAME: "matt"
  DB_PASSWORD: "password"

before_script:
  - apk add --no-cache docker-compose

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose up -d
    - docker-compose exec -T php php artisan migrate --seed
    - docker-compose exec -T php php artisan test
  after_script:
    - docker-compose down
