image: docker/compose:1.29.2

services:
  - docker:dind

stages:
  - build
  - test

variables:
  MYSQL_DATABASE: "laravel"
  MYSQL_USER: "matt"
  MYSQL_PASSWORD: "password"
  DB_CONNECTION: "mysql"
  DB_HOST: "database"
  DB_PORT: 3306
  DB_DATABASE: l"aravel"
  DB_USERNAME: "matt"
  DB_PASSWORD: "password"

before_script:
  - apk add --no-cache curl
  - apk add --no-cache mysql-client

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - cp .env.example .env
    - docker-compose up -d
    - docker-compose exec -T app composer install
    - docker-compose exec -T app php artisan key:generate
    - docker-compose exec -T app php artisan config:clear
    - docker-compose exec -T app php artisan migrate
    - docker-compose exec -T app php artisan test
    - docker-compose down
