image: docker/compose

services:
  - docker:dind

stages:
  - build
  - tests
  - code_standards

variables:
  DB_CONNECTION: mysql
  DB_HOST: database
  DB_PORT: 3306
  DB_DATABASE: laravel
  DB_USERNAME: matt
  DB_PASSWORD: password

build:
  stage: build
  script:
    - cp .env.example .env
    - docker-compose build
    - apk add mysql-client

tests:
  stage: tests
  script:
    - docker-compose up -d database app
    - docker-compose exec -T app npm install
    - docker-compose exec -T app npm run build
    - docker-compose run --rm artisan key:generate
    - docker-compose run --rm artisan cache:clear
    - docker-compose run --rm artisan config:clear
    - docker-compose run --rm artisan test
    - docker-compose exec -T app ./vendor/bin/pint --preset=psr12 --test

code_standards:
  stage: code_standards
  script:
    - docker-compose run --rm pint --test



