image: docker/compose

services:
  - docker:dind

stages:
  - build
  - cache_vendor
  - test

variables:
  DB_CONNECTION: mysql
  DB_HOST: database
  DB_PORT: 3306
  DB_DATABASE: laravel
  DB_USERNAME: matt
  DB_PASSWORD: password

build:
  stage: build
  script:
    - docker-compose build --pull
    - docker-compose up -d --compatibility

cache_vendor:
  stage: cache_vendor
  script:
    - docker-compose run --rm composer install --prefer-dist --no-dev --no-scripts --no-progress
    - docker-compose exec -T app npm install

test:
  stage: test
  script:
    - docker-compose exec -T app npm run build
    - docker-compose run --rm artisan key:generate
    - docker-compose run --rm artisan cache:clear
    - docker-compose run --rm artisan config:clear
    - docker-compose run --rm artisan test