version: '3.8'
services:
    app:
        container_name: app
        build:
            context: .
            target: php
        working_dir: /var/www
        volumes:
            -   ./:/var/www
        ports:
            - "80:80"
        depends_on:
            -   database
        networks:
            - laravel
    database:
        container_name: database
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
            - db-data:/var/lib/mysql
        networks:
            - laravel
    pma:
        container_name: pma
        image: phpmyadmin
        ports:
            - 9000:80
        environment:
            - PMA_HOST={$DB_HOST}
            - PMA_ARBITRARY=1
        networks:
            - laravel
    jenkins:
        image: jenkins/jenkins
        container_name: jenkins
        ports:
            - "8080:8080"
        networks:
            - laravel
    artisan:
        build:
            context: .
            target: php
        container_name: artisan
        volumes:
            - ./:/var/www:delegated
        depends_on:
            - database
        working_dir: /var/www
        entrypoint: [ 'php', '/var/www/artisan' ]
        networks:
            - laravel
    composer:
        image: composer:2.3.5
        container_name: composer
        volumes:
            - ./:/var/www
        working_dir: /var/www
        depends_on:
            - app
        user: '1000'
        entrypoint: [ 'composer', '--ignore-platform-reqs' ]
        networks:
            - laravel
    pint:
        build:
            context: .
            target: php
        container_name: pint
        volumes:
            - ./:/var/www:delegated
        working_dir: /var/www
        entrypoint: [ '/var/www/vendor/bin/pint', '--preset=psr12' ]
        networks:
            - laravel
    larastan:
        build:
            context: .
            target: php
        container_name: larastan
        volumes:
            - ./:/var/www:delegated
        working_dir: /var/www
        entrypoint: [ '/var/www/vendor/bin/phpstan','analyse','--memory-limit=2G' ]
        networks:
            - laravel
    phpmd:
        build:
            context: .
            target: php
        container_name: phpmd
        volumes:
            - ./:/var/www:delegated
        working_dir: /var/www
        entrypoint: [ '/var/www/vendor/bin/phpmd', 'app', 'gitlab', 'phpmd.xml' ]
        networks:
            - laravel
volumes:
    db-data:
networks:
    laravel:
        driver: bridge
